# This is a Service Weaver config file, written in TOML. Different sections of
# the config file configure various aspects of an application. See
# https://serviceweaver.dev/docs#config-files for details.

# The [serviceweaver] section is the only required section and configures the
# basics of an application, including the binary to run, the command line
# arguments to pass, and the environment variables to set.
[serviceweaver]
binary = "template"
# args = ["put", "command", "line", "arguments", "here"]
# env = ["PUT=foo", "ENV=bar", "VARS=baz", "HERE="]

# The [single] section configures the behavior of the app when deployed via
# `weaver single deploy`. See serviceweaver.dev/docs.html#single-process for
# more information about the single process deployer.
[single]
listeners.lis = {address="localhost:9000"}

# The [multi] section configures the behavior of the app when deployed via
# `weaver multi deploy`. See serviceweaver.dev/docs.html#multiprocess for more
# information about the multiprocess deployer.
[multi]
listeners.lis = {address="localhost:9000"}

# The [kube] section configures the behavior of the app when deployed via
# `weaver kube deploy`. See github.com/serviceweaver/weaver-kube for
# more information about the kubernetes deployer.
[kube]
listeners.lis = {public = true}
image = "DOCKER_HUB_USERNAME/app" # see `weaver kube deploy --help` for details

# The [gke] section configures the behavior of the app when deployed via
# `weaver gke deploy`. See serviceweaver.dev/docs.html#gke for more information
# about the GKE deployer.
[gke]
regions = ["us-west1"]
listeners.lis = {public_hostname = "app.example.com"}
